version: '3.9'

services:
  db:
    image: mysql
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
    ports:
      - '3306:3306'

platforms:
  mac:
    environment:
      DOCKER_MAC_PLATFORM: 'true'
